### ISSUE TITLE
Support for dynamic importing?

### ISSUE THREAD

**Issue by nagibmahfuj** [wasm-fmt/ruff_fmt#39]
I am using vite in react.js and in my async function I am trying to dynamically import the package.

```js
async function formatCode(code) {
    const init = await import("@wasm-fmt/ruff_fmt/vite");
    const { format } = await import("@wasm-fmt/ruff_fmt/vite");
    await init();
    return await format(code);
}
```

I am getting this error response:

```console
error
init is not a function
```

Does this package support this kind of dynamic importing?

**Comment by magic-akari** [comment]
The `init` you received is not a function because a dynamic import returns a module namespace object rather than its default export. see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#return_value
You can try the following code:

```JavaScript
    const init = await import("@wasm-fmt/ruff_fmt/vite").then(m => m.default);
```
